"""Migración inicial

Revision ID: 0a42f504f4b7
Revises: 
Create Date: 2021-09-17 01:20:48.687646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a42f504f4b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role_tat',
    sa.Column('role_id_tat', sa.Integer(), nullable=False),
    sa.Column('role_tat', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('role_id_tat')
    )
    op.create_table('user_tat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name_tat', sa.String(length=200), nullable=False),
    sa.Column('user_first_name_tat', sa.String(length=100), nullable=True),
    sa.Column('user_last_name_tat', sa.String(length=100), nullable=True),
    sa.Column('user_email_tat', sa.String(length=200), nullable=False),
    sa.Column('user_password_tat', sa.String(length=200), nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_role_tat.role_id_tat'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name_tat')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tat')
    op.drop_table('user_role_tat')
    # ### end Alembic commands ###
